services:
  db:
    image: postgres:15
    container_name: odoo-pruebas
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:17
    container_name: odoo-app-pruebas
    depends_on:
      - db
    ports:
      - "8070:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-api-pruebas
    depends_on:
      - odoo
    environment:
      ODOO_URL: http://odoo:8069
      ODOO_DB: pruebas-db
      ODOO_USERNAME: usuario_api
      ODOO_PASSWORD: "9753b595cc85dea7505e305fad021b2a06b96e2e"
      JSON_OUTPUT_DIR: /app/generated_json
      JSON_PRESTASHOP_OUTPUT_DIR: /app/json_prestashop
      PRESTASHOP_URL: http://prestashop
      PRESTASHOP_API_KEY: "CEHARES1GC5SVMP8JMLVMEF7ZMUA735A"
      PRESTASHOP_LANGUAGE_ID: "1"
      PRESTASHOP_HOST_HEADER: "localhost:8081"
    ports:
      - "8091:8000"
    volumes:
      - ./generated_json:/app/generated_json
      - ./json_prestashop:/app/json_prestashop
    restart: always

  prestashop-db:
    image: mariadb:11
    container_name: prestashop-db-pruebas
    environment:
      MARIADB_DATABASE: prestashop
      MARIADB_USER: prestashop
      MARIADB_PASSWORD: prestashop
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - prestashop-db-data:/var/lib/mysql
    restart: always

  prestashop:
    image: prestashop/prestashop:8
    container_name: prestashop-app-pruebas
    depends_on:
      - prestashop-db
    environment:
      DB_SERVER: prestashop-db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: prestashop
      PS_DOMAIN: localhost:8081
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-dev
    ports:
      - "8081:80"
    volumes:
      - prestashop-data:/var/www/html
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data:
  prestashop-db-data:
  prestashop-data:
 